### ISSUE TITLE
How to recognize the miR-family?

### ISSUE THREAD

**Issue by PessieXiong** [alanlamsiu/miRDeep-P2_pipeline#10]
Hi,

I've run the result as your pipeline shown, but I'm having trouble understanding the output:

1.All the predicted miRNAs are entitled as miRDP2_mature_x. How can we name them according to their miRNA families?
2.In step 2, the known IDs are blasted in miRBase with all species. Shouldn't we blast with the specific species? For example, in this miRDP2_mature_known.txt, the known ID includes "ata-miR171a-3p&aof-miR479&stu-miR479&mdm-miR171i& ". How can we determine the miRNA family when the known family is not identical?

These are the questions I have while trying to understand the output. Looking forward to your reply.

**Comment by alanlamsiu** [comment]
Hi @PessieXiong,

Your first question is related to miRNA annotation and you can refer to [2. Annotation of miRNA
](https://github.com/TF-Chan-Lab/miRDeep-P2_pipeline?tab=readme-ov-file#2-annotation-of-mirna). This is also related to your second question. It is your choise which database to serve as the reference. Sometimes, the species of interest does not have a good miRNA annotation and you may want to borrow the annotation from other, probably closely related, species. In the example you are showing here, the four referenc miRNAs share the same sequence.

```
>ata-miR171a-3p
UGAGCCGAACCAAUAUCACUC
>aof-miR479
UGAGCCGAACCAAUAUCACUC
>stu-miR479
UGAGCCGAACCAAUAUCACUC
>mdm-miR171i
UGAGCCGAACCAAUAUCACUC
```

The naming of miRNA family can be different in different species, e.g. it is called miR171 in ATa and MDm, while miR479 in AOf and STu. However, it is clear that they all refer to the same sequence. To avoid ambiguity, I prefer using the sequence as identifier, while keeping track of all miRNAs in the reference database that are related.
